[package]
name = "FlorenciaEngine"
version = "0.0.1"
edition = "2021"
authors = ["Awesomeness211i"]

[dependencies]
winit = { version = "*" }
ash = { version = "*", features = ["debug"] }
anyhow = { version = "*" }
ash-window = { version = "*" }
