[package]
name = "FloEditor"
version = "0.0.1"
edition = "2021"
authors = ["Awesomeness211i"]

[lints]
workspace = true

[dependencies]
FlorenciaEngine = { path = "../FlorenciaEngine" }
anyhow = { version = "*" }
